const state={products:[],filtered:[],page:1,perPage:12,filters:{category:new Set(),subcategory:new Set(),brand:new Set()},search:"",sort:"featured"};
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const grid=document.getElementById("productGrid");
const pagination=document.getElementById("pagination");
const resultCount=document.getElementById("resultCount");
const template=document.getElementById("productTemplate");

function uniqueCount(items,key){const map=new Map();items.forEach(p=>{const v=p[key]||"Sin clasificar";map.set(v,(map.get(v)||0)+1)});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],"es"))}
function renderFilter(containerId,key,setName){const el=document.getElementById(containerId);el.innerHTML="";uniqueCount(state.products,key).forEach(([value,count])=>{const row=document.createElement("div");row.className="filter-option";const safe=`${setName}-${value}`.replace(/[^a-zA-Z0-9_-]/g,"-");row.innerHTML=`<label for="${safe}"><input id="${safe}" type="checkbox" value="${value}"><span>${value}</span></label><span class="filter-count">${count}</span>`;row.querySelector("input").addEventListener("change",e=>{e.target.checked?state.filters[setName].add(value):state.filters[setName].delete(value);state.page=1;applyFilters()});el.appendChild(row)})}
function applyFilters(){const q=state.search.trim().toLowerCase();state.filtered=state.products.filter(p=>{const hay=[p.codigo,p.nombre,p.categoria,p.subcategoria,p.marca,p.descripcion].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!state.filters.category.size||state.filters.category.has(p.categoria))&&(!state.filters.subcategory.size||state.filters.subcategory.has(p.subcategoria))&&(!state.filters.brand.size||state.filters.brand.has(p.marca))});if(state.sort==="name-asc")state.filtered.sort((a,b)=>a.codigo.localeCompare(b.codigo,"es"));if(state.sort==="price-asc")state.filtered.sort((a,b)=>(a.precio_oferta||a.precio)-(b.precio_oferta||b.precio));if(state.sort==="price-desc")state.filtered.sort((a,b)=>(b.precio_oferta||b.precio)-(a.precio_oferta||a.precio));render()}
function render(){grid.innerHTML="";const total=state.filtered.length;const pages=Math.max(1,Math.ceil(total/state.perPage));if(state.page>pages)state.page=pages;const start=(state.page-1)*state.perPage;const items=state.filtered.slice(start,start+state.perPage);resultCount.textContent=`${total} producto${total===1?"":"s"} disponible${total===1?"":"s"}`;if(!items.length){grid.innerHTML='<div class="empty-state"><h3>No encontramos productos</h3><p>Prueba con otro código, marca o aplicación.</p></div>'}items.forEach(p=>{const node=template.content.cloneNode(true);const card=node.querySelector(".product-card");const img=node.querySelector(".product-image");img.src=p.imagen;img.alt=`${p.nombre} ${p.codigo}`;node.querySelector(".product-code").textContent=p.codigo;node.querySelector(".product-brand").textContent=p.marca;node.querySelector(".product-name").textContent=p.nombre;node.querySelector(".product-application").textContent=p.subcategoria;const current=node.querySelector(".current-price");const old=node.querySelector(".old-price");if(p.precio_oferta){current.textContent=money.format(p.precio_oferta);old.textContent=money.format(p.precio)}else{current.textContent=money.format(p.precio);old.remove()}const detail=node.querySelector(".detail-button");detail.href=p.ficha_url||"#";if(!p.ficha_url){detail.style.display="none"}const quote=node.querySelector(".quote-button");quote.href=`https://wa.me/56922108234?text=${encodeURIComponent(`Hola, necesito cotizar ${p.nombre} código ${p.codigo}.`)}`;grid.appendChild(node)});renderPagination(pages)}
function renderPagination(pages){pagination.innerHTML="";if(pages<=1)return;const add=(label,page,disabled=false,active=false)=>{const b=document.createElement("button");b.textContent=label;b.disabled=disabled;b.classList.toggle("active",active);b.addEventListener("click",()=>{state.page=page;render();window.scrollTo({top:document.querySelector(".products-area").offsetTop-90,behavior:"smooth"})});pagination.appendChild(b)};add("‹",Math.max(1,state.page-1),state.page===1);for(let i=1;i<=pages;i++){if(pages>7&&Math.abs(i-state.page)>2&&i!==1&&i!==pages){if((i===2&&state.page>4)||(i===pages-1&&state.page<pages-3)){const s=document.createElement("span");s.textContent="…";s.style.padding="12px 4px";pagination.appendChild(s)}continue}add(i,i,false,i===state.page)}add("›",Math.min(pages,state.page+1),state.page===pages)}
async function init(){try{const res=await fetch("../data/productos.json");if(!res.ok)throw new Error("No se pudo cargar el catálogo");state.products=await res.json();state.filtered=[...state.products];renderFilter("categoryFilters","categoria","category");renderFilter("subcategoryFilters","subcategoria","subcategory");renderFilter("brandFilters","marca","brand");applyFilters()}catch(err){grid.innerHTML=`<div class="empty-state"><h3>Error al cargar el catálogo</h3><p>${err.message}</p></div>`;resultCount.textContent="Catálogo no disponible"}}
document.getElementById("searchInput").addEventListener("input",e=>{state.search=e.target.value;state.page=1;applyFilters()});
document.getElementById("sortSelect").addEventListener("change",e=>{state.sort=e.target.value;state.page=1;applyFilters()});
document.getElementById("clearFilters").addEventListener("click",()=>{state.filters.category.clear();state.filters.subcategory.clear();state.filters.brand.clear();state.search="";document.getElementById("searchInput").value="";document.querySelectorAll('.filter-options input').forEach(i=>i.checked=false);state.page=1;applyFilters()});
document.querySelectorAll(".filter-title").forEach(btn=>btn.addEventListener("click",()=>{const options=btn.nextElementSibling;const open=btn.getAttribute("aria-expanded")==="true";btn.setAttribute("aria-expanded",String(!open));btn.querySelector("span").textContent=open?"+":"−";options.hidden=open}));
const menuButton=document.querySelector(".menu-toggle");const nav=document.querySelector(".main-nav");menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});
init();